"""add user activities and new user fields

Revision ID: 48d09036fcb7
Revises: 796533bda978
Create Date: 2026-06-19 00:22:02.019204

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48d09036fcb7"
down_revision: Union[str, None] = "796533bda978"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_activities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("team_name", sa.String(length=200), nullable=False),
        sa.Column("position", sa.String(length=100), nullable=False),
        sa.Column("start_date", sa.BigInteger(), nullable=False),
        sa.Column("end_date", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="activitystatus"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_activities_user_id", "user_activities", ["user_id"], unique=False
    )
    op.add_column("users", sa.Column("student_id", sa.String(length=50), nullable=True))
    op.add_column(
        "users", sa.Column("department", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "department")
    op.drop_column("users", "student_id")
    op.drop_index("idx_activities_user_id", table_name="user_activities")
    op.drop_table("user_activities")
    # ### end Alembic commands ###
